sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -y update
- sudo apt-get -y install build-essential
- sudo apt-get -y install g++-5
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
- g++ --version
install:
- pip install codecov
- pip install .
script:
- python setup.py test
after_success:
  - codecov